### ISSUE TITLE
Incompatible with Crystal 0.35.1

### ISSUE THREAD

**Issue by manveru** [taylorthurlow/thicket#7]
The tests are still running against 0.32, building the shard myself locally I get:

```
crystal build -o /build/source/bin/thicket src/thicket.cr --release --progress
Error target thicket failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/thicket/log.cr:29:12

 29 | rescue Errno
             ^
Error: Errno is not a subclass of Exception
```

**Comment by taylorthurlow** [comment]
Hmm interesting, I swear I just built against 0.35.1. I'll try and fix this soon. Thanks for the report!

**Comment by taylorthurlow** [comment]
@manveru It looks like you're not using the latest code - if you're building against master, pull the latest version and it should build. I fixed this issue like 6 weeks ago.

**Comment by manveru** [comment]
Sorry, my bad, I had the wrong revision indeed.
